### ISSUE TITLE
support for meson pre 0.54

### ISSUE THREAD

**Issue by r3pek** [Davester47/vscode-meson-tools#1]
Hey there!

Thanks for taking time working on a meson plugin (really useful for open source projects)
Can I request that you check meson version prior to run "meson compile"?
I'ts a feature that it's only available on 0.54 (0.55 if we count --verbose flag), and not many Linux distros have that version.

**Comment by Davester47** [comment]
Thanks for letting me know about this. I didn't realize that `meson compile` was a relatively new feature. I'll get to work on adding a version check for Meson.

**Comment by Davester47** [comment]
Alright, I think I've fixed it, however the only Meson backend that will work on versions older than 0.54.0 is ninja. I've pushed version 0.1.2 to the Extension Marketplace. Let me know if this worked for you.

**Comment by r3pek** [comment]
@Davester47 it might be a separate issue, but for some reason, tasks aren't getting populated with the meson targets (this happened before, it's not specific to this version), so vscode just tries to compile the .c file as a generic "program", without meson/ninja.
but the change you made looks like it should work, it's just the meson tasks that aren't getting generated.

**Comment by r3pek** [comment]
ok.... after a few more testing i was able to regenerate the meson targets in launch.json file.

it still tries to run `meson compile` probably because tasks.json still has this:
```
{
      "type": "shell",
      "label": "Meson: Build Project",
      "command": "meson compile",
      "options": {
          "cwd": "/home/r3pek/projects/libratbag/builddir"
      }
},
```

**Comment by r3pek** [comment]
yeah... you forgot to change here too ;)
https://github.com/Davester47/vscode-meson-tools/blob/master/src/debug.ts#L80-L88

**Comment by Davester47** [comment]
@r3pek, sorry for taking so long to get back to you. When you first press F5 to configure debugging, it will try to run the source file as a generic program, but it will almost certainly fail. The reason the extension prompts you to do this is that the C/C++ extension will create a configuration that has the right debugger, although it doesn't work. I use that to create the launch configurations for each target.

I think I've got this fixed now with version 0.1.3. It might take a few minutes for the new extension to show up in VS Code.

**Comment by r3pek** [comment]
confirmed working on 0.1.3 ;) thx
